version: '3.8'

services:
  express-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-backend
    env_file:
      - .env
    ports:
      - "5555:5555"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - express-backend-network

networks:
  express-backend-network:
    driver: bridge
